### ISSUE TITLE
csi escape sequences are broken

### ISSUE THREAD

**Issue by rnoth** [josuah/iode#1]
a lot of aplications shell out to $PAGER and embed raw escape sequences in their output, such as`git-diff(1)` and `man(1)`. iode previously was able to handle this just fine, but has changed sometime between when I first cloned it and the newest commit.

I'm not against it being binary-clean, so perhaps providing an option for not interpretting control bytes or so? iode seems to be unusable as a pager otherwise.

**Comment by josuah** [comment]
Yes, in the long run I want it to be some editor, so I temporarily dropped the escape sequences.

But fortunately, it is very easy to get it working at a minimal level: most escape sequences start by Escape, then have digits and columns and end with a letter.

I'm adding option support and doing it now...

**Comment by josuah** [comment]
It should work by 537b5d39e062df8ab1479b6efaa187d185f03dca.

I have to document the flag switching, but in the meantime:

`iode +Flag +s` enable the flags `F`, `l`, `a`, `g`, and `s`, and `iode -Flag -s` disable them.

While started, you can press `+` / `-` and a key to enable / disable a flag.
